package renderer

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/telecraft-dev/telecraft/internal/ownership"
)

// CodeOwners renders the generated code-ownership projection from the team
// tree (ADR-0018, ADR-0028 §4): `teams.yaml` and the object `owner:` fields
// are the source; this file is a cache in the configured forge's dialect
// whose loss loses nothing. The GitHub dialect is the first implementation
// of the forge seam, not the requirement — an owner id projects to the
// forge handle `@<owner-id>`.
//
// Each team owns its authored subtree and its rendered artefacts, and every
// line carries the owners of the team *plus its ancestors* — the review
// reach derives from the tree, never from the directory shape (ADR-0027
// §1): a PR whose render touches a team's Component requires that team's
// review, and the ancestors who govern it keep their say.
func CodeOwners(tree ownership.Tree) []byte {
	var buf bytes.Buffer
	buf.WriteString("# Generated by the telecraft renderer from teams.yaml — this file is a\n")
	buf.WriteString("# projection of the team tree, never the source; humans edit teams.yaml\n")
	buf.WriteString("# and object owner fields instead (ADR-0018, ADR-0028 §4). GitHub dialect.\n")

	for _, id := range sortedKeys(tree.Teams) {
		handles := chainHandles(tree, id)
		if len(handles) == 0 {
			// A CODEOWNERS line with no owner assigns review to nobody;
			// omitting the line leaves the path to the repo default, which
			// is the honest projection of an ownerless chain.
			continue
		}
		buf.WriteString("\n")
		fmt.Fprintf(&buf, "/teams/%s/ %s\n", id, strings.Join(handles, " "))
		fmt.Fprintf(&buf, "/rendered/%s/ %s\n", id, strings.Join(handles, " "))
	}
	return buf.Bytes()
}

// chainHandles collects the forge handles for a team and its ancestors,
// nearest first, deduplicated in that order.
func chainHandles(tree ownership.Tree, id ownership.TeamID) []string {
	var out []string
	seen := map[ownership.OwnerID]bool{}
	for t := id; t != ""; t = tree.Teams[t].Parent {
		for _, o := range tree.Teams[t].Owners {
			if !seen[o] {
				seen[o] = true
				out = append(out, "@"+string(o))
			}
		}
	}
	return out
}
