package renderer

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/telecraft-dev/telecraft/internal/blueprint"
	"github.com/telecraft-dev/telecraft/internal/catalogue"
	"github.com/telecraft-dev/telecraft/internal/livecheck"
)

// emitCollector builds one Tier's plain otelcol YAML (REQ-032): component
// definitions per class section, then the service block wiring pipelines in
// authored lane order, stamped with the commit SHA and the node-unique
// identifying attribute. The emission order is fixed and every map is
// walked sorted: identical inputs produce byte-identical artefacts, the
// property CI recomputes and diffs (ADR-0028 §2).
// Beside the artefact it returns the exporter side of every lane it wired,
// which is the Hop-to-exporter join of ADR-0040 §1: this function is the
// one place that knows, without guessing, which exporters a signal leaves
// this Tier through.
func emitCollector(in Inputs, tier Tier, bp blueprint.Blueprint, instances map[string]instance) ([]byte, LaneExporters, []string) {
	ctx := fmt.Sprintf("tier %q", tier.ID())
	var problems []string

	// Compile the signal lanes first: the pipelines decide which sections
	// the artefact needs.
	pipelines := map[blueprint.Signal]pipeline{}
	for _, s := range blueprint.Signals {
		entries := bp.Lane(s)
		if len(entries) == 0 {
			continue
		}
		p, laneProblems := compileLane(in.Estate, bp, string(s), entries, ctx)
		problems = append(problems, laneProblems...)
		pipelines[s] = p
	}

	// The live-check branch (ADR-0034 §5): an opted-in Tier tees one
	// pipeline per wired lane, sharing the lane's receivers, sampling at
	// the resolved rate, exporting only to the live-check destination.
	// The branch sits beside the lanes, never inside them, so the main
	// pipelines are identical with and without it and the tap dying costs
	// findings, never data (REQ-002). Profiles are not teed: the tap
	// assesses spans, metrics and logs, and a profile finding has no
	// place in the platform's signal vocabulary (livecheck.SignalFor).
	var teedSignals []blueprint.Signal
	if tier.LiveCheck != nil && in.LiveCheck != nil {
		for _, s := range blueprint.Signals {
			if s == blueprint.Profiles {
				continue
			}
			if _, wired := pipelines[s]; wired {
				teedSignals = append(teedSignals, s)
			}
		}
	}

	// Record the exporter side while it is being decided (ADR-0040 §1).
	// The record is taken before the untrusted-Hop strip is prepended,
	// because the strip is a generated processor and changes nothing about
	// where the lane's data leaves. The teed live-check pipelines are
	// recorded like any other wired pipeline: their out-rate is a real
	// per-exporter reading, and the record's contract is to describe every
	// pipeline the artefact wires.
	var exporters LaneExporters
	for _, s := range blueprint.Signals {
		p, wired := pipelines[s]
		if !wired {
			continue
		}
		if exporters == nil {
			exporters = LaneExporters{}
		}
		exporters[string(s)] = append([]string(nil), p.exporters...)
	}
	for _, s := range teedSignals {
		exporters[liveCheckPipelineName(string(s))] = []string{livecheck.ExporterID}
	}

	// The untrusted-Hop strip (REQ-034, ADR-0007): any untrusted arrival
	// makes the whole intake untrusted, because one Tier renders one artefact for
	// all its collectors, so intake cannot split per Hop. The generated
	// processor runs first in every signal pipeline: nothing may observe the
	// platform namespace on inbound data before the strip.
	strip := tier.Untrusted() && len(pipelines) > 0
	if strip {
		for s, p := range pipelines {
			p.processors = append([]string{StripProcessorID}, p.processors...)
			pipelines[s] = p
		}
	}

	// service.extensions holds the collector-wide extensions in authored
	// order (ADR-0024 §2). Anything but an extension cannot live there.
	var serviceExtensions []string
	seenExt := map[string]bool{}
	for _, e := range bp.Extensions {
		c, ok := resolve(in.Estate, bp, e.Reference())
		if !ok {
			continue // already a mechanical refusal from resolveInstances
		}
		if c.Class != catalogue.Extension {
			problems = append(problems, fmt.Sprintf("%s: the extensions block references %s, which is a %s. Only extensions can go there.", ctx, c.ID(), c.Class))
			continue
		}
		id := RenderedID(c)
		if !seenExt[id] {
			seenExt[id] = true
			serviceExtensions = append(serviceExtensions, id)
		}
	}

	if len(problems) > 0 {
		return nil, nil, problems
	}

	root := mapping()
	root.HeadComment = fmt.Sprintf(
		"Generated by the telecraft renderer. Do not edit by hand: change the source in git and render again.\nTier %s (%s), Blueprint %s, commit %s.",
		tier.ID(), tier.Environment, tier.Binding(), in.Commit)

	// Definition sections, one per class, ids sorted within each.
	sections := map[catalogue.Class]*yaml.Node{}
	for _, id := range sortedKeys(instances) {
		c := instances[id].comp
		section, ok := sections[c.Class]
		if !ok {
			section = mapping()
			sections[c.Class] = section
		}
		def, err := configNode(c.Config)
		if err != nil {
			return nil, nil, []string{fmt.Sprintf("%s: Component %s: %v", ctx, c.ID(), err)}
		}
		appendPair(section, scalar(id), def)
	}
	if strip {
		section, ok := sections[catalogue.Processor]
		if !ok {
			section = mapping()
			sections[catalogue.Processor] = section
		}
		def, err := configNode(map[string]any{
			"actions": []any{map[string]any{"action": "delete", "pattern": `^telecraft\.`}},
		})
		if err != nil {
			return nil, nil, []string{fmt.Sprintf("%s: %v", ctx, err)}
		}
		key := scalar(StripProcessorID)
		key.HeadComment = "Generated: this Tier receives data over an untrusted Hop, so this\nprocessor drops every telecraft.* attribute on arrival. Identity\ncomes from this Tier's own stamps, never from inbound data."
		// The strip runs first in every pipeline, so its definition leads
		// the section too, keeping the artefact legible top to bottom.
		prependPair(section, key, def)
	}
	if len(teedSignals) > 0 {
		rate := in.LiveCheck.SampleRate(tier)
		section, ok := sections[catalogue.Processor]
		if !ok {
			section = mapping()
			sections[catalogue.Processor] = section
		}
		def, err := configNode(map[string]any{"sampling_percentage": rate})
		if err != nil {
			return nil, nil, []string{fmt.Sprintf("%s: %v", ctx, err)}
		}
		key := scalar(LiveCheckSamplerID)
		key.HeadComment = fmt.Sprintf("Generated: samples %s per cent of each lane's intake for the\nlive-check service.", formatRate(rate))
		appendPair(section, key, def)

		section, ok = sections[catalogue.Exporter]
		if !ok {
			section = mapping()
			sections[catalogue.Exporter] = section
		}
		def, err = configNode(map[string]any{"endpoint": in.LiveCheck.Resolve(tier.Environment)})
		if err != nil {
			return nil, nil, []string{fmt.Sprintf("%s: %v", ctx, err)}
		}
		key = scalar(livecheck.ExporterID)
		key.HeadComment = "Generated: carries the live-check sample. Only the live-check\npipelines export through it; the data lanes do not."
		appendPair(section, key, def)
	}
	for _, class := range []struct {
		class   catalogue.Class
		section string
	}{
		{catalogue.Receiver, "receivers"},
		{catalogue.Processor, "processors"},
		{catalogue.Exporter, "exporters"},
		{catalogue.Connector, "connectors"},
		{catalogue.Extension, "extensions"},
	} {
		if s, ok := sections[class.class]; ok {
			appendPair(root, scalar(class.section), s)
		}
	}

	// The service block: extensions, pipelines in the fixed signal order,
	// then telemetry with the identity stamps.
	service := mapping()
	if len(serviceExtensions) > 0 {
		appendPair(service, scalar("extensions"), sequence(serviceExtensions))
	}
	if len(pipelines) > 0 {
		pipelinesNode := mapping()
		for _, s := range blueprint.Signals {
			p, ok := pipelines[s]
			if !ok {
				continue
			}
			laneNode := mapping()
			appendPair(laneNode, scalar("receivers"), sequence(p.receivers))
			if len(p.processors) > 0 {
				appendPair(laneNode, scalar("processors"), sequence(p.processors))
			}
			appendPair(laneNode, scalar("exporters"), sequence(p.exporters))
			appendPair(pipelinesNode, scalar(string(s)), laneNode)
		}
		for i, s := range teedSignals {
			// The teed branch shares the lane's receivers only: the lane's
			// own processors stay out of it, and the strip stays in, because
			// nothing may observe the platform namespace on inbound data
			// before the strip, the live-check exporter included (ADR-0007).
			processors := []string{LiveCheckSamplerID}
			if strip {
				processors = []string{StripProcessorID, LiveCheckSamplerID}
			}
			laneNode := mapping()
			appendPair(laneNode, scalar("receivers"), sequence(pipelines[s].receivers))
			appendPair(laneNode, scalar("processors"), sequence(processors))
			appendPair(laneNode, scalar("exporters"), sequence([]string{livecheck.ExporterID}))
			key := scalar(liveCheckPipelineName(string(s)))
			if i == 0 {
				key.HeadComment = "Generated: the live-check pipelines. Each shares its lane's\nreceivers and exports only to the live-check service."
			}
			appendPair(pipelinesNode, key, laneNode)
		}
		appendPair(service, scalar("pipelines"), pipelinesNode)
	}

	resource := mapping()
	nodeKey := scalar("k8s.node.name")
	nodeKey.HeadComment = fmt.Sprintf("Node-unique identity via the Downward API: the install guide sets\n%s from spec.nodeName, so one DaemonSet manifest\ngives each node its own identity.", NodeEnvVar)
	appendPair(resource, nodeKey, scalar(fmt.Sprintf("${env:%s}", NodeEnvVar)))
	commitKey := scalar(CommitAttribute)
	commitKey.HeadComment = "The artefact carries its own identity: the commit it was rendered from."
	appendPair(resource, commitKey, scalar(in.Commit))
	tierKey := scalar(TierAttribute)
	tierKey.HeadComment = "The Tier this artefact belongs to. With the commit stamp, it joins\neach self-telemetry reading back to the artefact that produced it."
	appendPair(resource, tierKey, scalar(tier.ID()))
	telemetry, telProblems := emitSelfTelemetry(in, resource, tier.Environment, ctx)
	if len(telProblems) > 0 {
		return nil, nil, telProblems
	}
	appendPair(service, scalar("telemetry"), telemetry)

	appendPair(root, scalar("service"), service)

	artefact, marshalProblems := marshalDocument(root)
	if len(marshalProblems) > 0 {
		return nil, nil, marshalProblems
	}
	return artefact, exporters, nil
}

// emitSelfTelemetry builds the `service::telemetry` block: the identity
// resource plus OTLP-push of the collector's internal metrics (level
// normal, periodic reader) and logs (batch processor) to the estate's
// declared destination, resolved for this Environment (REQ-053, ADR-0039
// §1 to §2). The renderer owns this block; Blueprints never author it
// (boundary against ADR-0024's collector-wide section). Internal traces
// stay off in v1: experimental upstream, and no claim consumes them. The
// localhost Prometheus default is left untouched, so local debugging keeps
// working.
//
// Each signal's endpoint is completed here, not authored: over
// http/protobuf the estate's base endpoint gains `/v1/metrics` or
// `/v1/logs`, because these exporters append nothing themselves (ADR-0053,
// issue #109).
func emitSelfTelemetry(in Inputs, resource *yaml.Node, environment, ctx string) (*yaml.Node, []string) {
	telemetry := mapping()
	appendPair(telemetry, scalar("resource"), resource)

	// One exporter per signal, not one shared between them: these are the
	// OTel SDK's declarative-config exporters, which take `endpoint` as the
	// complete URL and append nothing, so the two blocks address two URLs
	// (ADR-0053 §1).
	exporter := func(signal string) map[string]any {
		return map[string]any{
			"otlp": map[string]any{
				"protocol": in.SelfTelemetry.protocol(),
				"endpoint": in.SelfTelemetry.signalEndpoint(environment, signal),
			},
		}
	}
	metrics, err := configNode(map[string]any{
		"level":   "normal",
		"readers": []any{map[string]any{"periodic": map[string]any{"exporter": exporter("metrics")}}},
	})
	if err != nil {
		return nil, []string{fmt.Sprintf("%s: self-telemetry metrics block: %v", ctx, err)}
	}
	metricsKey := scalar("metrics")
	metricsKey.HeadComment = "Self-telemetry goes to the estate's declared destination over its\nown exporter and connection, never through this Tier's data\npipelines. Internal traces stay off in v1. These exporters take the\nendpoint as the complete URL, so the renderer adds the signal path\nhere rather than at run time."
	appendPair(telemetry, metricsKey, metrics)

	logs, err := configNode(map[string]any{
		"processors": []any{map[string]any{"batch": map[string]any{"exporter": exporter("logs")}}},
	})
	if err != nil {
		return nil, []string{fmt.Sprintf("%s: self-telemetry logs block: %v", ctx, err)}
	}
	appendPair(telemetry, scalar("logs"), logs)
	return telemetry, nil
}

// emitSupervisor builds the Supervisor config served beside a Tier's
// collector artefact (REQ-032). The generated defaults are ADR-0010's
// install hard rules: remote config explicitly enabled, rollback on, state
// on a durable path.
func emitSupervisor(in Inputs, tier Tier) []byte {
	root := mapping()
	root.HeadComment = fmt.Sprintf(
		"Generated by the telecraft renderer. Do not edit by hand: change the source in git and render again.\nSupervisor config for Tier %s, commit %s.",
		tier.ID(), in.Commit)

	server := mapping()
	appendPair(server, scalar("endpoint"), scalar(tier.Serving.Endpoint))
	appendPair(root, scalar("server"), server)

	capabilities := mapping()
	acceptsKey := scalar("accepts_remote_config")
	acceptsKey.HeadComment = "Off upstream by default; on here so the Supervisor accepts served config."
	appendPair(capabilities, acceptsKey, boolScalar(true))
	appendPair(capabilities, scalar("reports_effective_config"), boolScalar(true))
	appendPair(capabilities, scalar("reports_health"), boolScalar(true))
	appendPair(root, scalar("capabilities"), capabilities)

	agent := mapping()
	rollbackKey := scalar("automatic_config_rollback")
	rollbackKey.HeadComment = "Off upstream by default; on here so a failed config reverts on its own."
	appendPair(agent, rollbackKey, boolScalar(true))
	appendPair(root, scalar("agent"), agent)

	storage := mapping()
	dirKey := scalar("directory")
	dirKey.HeadComment = "Mount a durable volume here: an ephemeral directory gives the\ncollector a new identity every time the pod is replaced."
	appendPair(storage, dirKey, scalar(SupervisorStorageDir))
	appendPair(root, scalar("storage"), storage)

	out, _ := marshalDocument(root)
	return out
}

// emitUnmatched builds the Unmatched artefact (ADR-0030): served to a
// collector matching no Tier selector. Commit-stamped and self-telemetry
// only, with no data pipelines, so the one case where the platform talks to an
// ungoverned thing collects nothing while staying maximally visible: alive,
// stamped, labelled governed-by-nobody. Non-empty by construction, which is
// what lets the server honour the never-serve-empty rule (ADR-0010 rule 6)
// without inventing config of its own.
func emitUnmatched(in Inputs) []byte {
	root := mapping()
	root.HeadComment = fmt.Sprintf(
		"Generated by the telecraft renderer. Do not edit by hand: change the source in git and render again.\nThe Unmatched artefact, commit %s: served to a collector\nthat matches no Tier selector. Self-telemetry only, no data\npipelines. This is not the quarantine destination, which routes\ndata rather than collectors.",
		in.Commit)

	resource := mapping()
	nodeKey := scalar("k8s.node.name")
	nodeKey.HeadComment = fmt.Sprintf("Node-unique identity via the Downward API: the install guide sets\n%s from spec.nodeName, so one DaemonSet manifest\ngives each node its own identity.", NodeEnvVar)
	appendPair(resource, nodeKey, scalar(fmt.Sprintf("${env:%s}", NodeEnvVar)))
	commitKey := scalar(CommitAttribute)
	commitKey.HeadComment = "The artefact carries its own identity: the commit it was rendered from."
	appendPair(resource, commitKey, scalar(in.Commit))
	unmatchedKey := scalar(UnmatchedAttribute)
	unmatchedKey.HeadComment = "Marks this collector as matching no Tier, so the console can\nshow it and offer to onboard it."
	appendPair(resource, unmatchedKey, boolScalar(true))

	// No Tier stamp: an unmatched collector has none, which is exactly
	// what the label above says. The push blocks still render: ADR-0030
	// made this artefact self-telemetry-only, and ADR-0039 §1 makes the
	// push mandatory everywhere. No Environment either, so the estate
	// endpoint resolves.
	telemetry, problems := emitSelfTelemetry(in, resource, "", "unmatched artefact")
	if len(problems) > 0 {
		// The blocks are built from validated inputs and plain literals;
		// refusal here would mean a renderer bug, and the render's contract
		// is complete-or-refused, so make it loud.
		panic(strings.Join(problems, "; "))
	}
	service := mapping()
	appendPair(service, scalar("telemetry"), telemetry)
	appendPair(root, scalar("service"), service)

	out, _ := marshalDocument(root)
	return out
}

// mapping returns an empty block-style mapping node.
func mapping() *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
}

// scalar returns a plain scalar node for a string value.
func scalar(s string) *yaml.Node {
	n := &yaml.Node{}
	n.SetString(s)
	return n
}

func boolScalar(b bool) *yaml.Node {
	n := &yaml.Node{}
	if err := n.Encode(b); err != nil {
		panic(err) // encoding a bool cannot fail
	}
	return n
}

// sequence returns a block sequence of plain scalars.
func sequence(values []string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, v := range values {
		n.Content = append(n.Content, scalar(v))
	}
	return n
}

func appendPair(m, key, value *yaml.Node) {
	m.Content = append(m.Content, key, value)
}

func prependPair(m, key, value *yaml.Node) {
	m.Content = append([]*yaml.Node{key, value}, m.Content...)
}

// configNode encodes a Component's opaque config body with every mapping
// recursively sorted by key. The body is authored YAML and its in-memory
// form is a Go map, so nothing about it has an order of its own. Sorting
// is what makes the emission a pure function of content (ADR-0028 §2).
func configNode(v any) (*yaml.Node, error) {
	if v == nil {
		return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Style: yaml.FlowStyle}, nil
	}
	n := &yaml.Node{}
	if err := n.Encode(v); err != nil {
		return nil, fmt.Errorf("config does not encode to YAML: %w", err)
	}
	sortMappings(n)
	return n, nil
}

// sortMappings sorts every mapping in the node tree by key, in place.
func sortMappings(n *yaml.Node) {
	for _, c := range n.Content {
		sortMappings(c)
	}
	if n.Kind != yaml.MappingNode {
		return
	}
	pairs := make([][2]*yaml.Node, 0, len(n.Content)/2)
	for i := 0; i+1 < len(n.Content); i += 2 {
		pairs = append(pairs, [2]*yaml.Node{n.Content[i], n.Content[i+1]})
	}
	sort.SliceStable(pairs, func(i, j int) bool { return pairs[i][0].Value < pairs[j][0].Value })
	n.Content = n.Content[:0]
	for _, p := range pairs {
		n.Content = append(n.Content, p[0], p[1])
	}
}

// marshalDocument renders a root node with the repo's two-space indent.
func marshalDocument(root *yaml.Node) ([]byte, []string) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, []string{fmt.Sprintf("artefact does not encode to YAML: %v", err)}
	}
	if err := enc.Close(); err != nil {
		return nil, []string{fmt.Sprintf("artefact does not encode to YAML: %v", err)}
	}
	return buf.Bytes(), nil
}
