package renderer

import (
	"bytes"
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"

	"github.com/telecraft-dev/telecraft/internal/blueprint"
	"github.com/telecraft-dev/telecraft/internal/catalogue"
)

// emitCollector builds one Tier's plain otelcol YAML (REQ-032): component
// definitions per class section, then the service block wiring pipelines in
// authored lane order, stamped with the commit SHA and the node-unique
// identifying attribute. The emission order is fixed and every map is
// walked sorted — identical inputs produce byte-identical artefacts, the
// property CI recomputes and diffs (ADR-0028 §2).
func emitCollector(in Inputs, tier Tier, bp blueprint.Blueprint, instances map[string]instance) ([]byte, []string) {
	ctx := fmt.Sprintf("tier %q", tier.ID())
	var problems []string

	// Compile the signal lanes first: the pipelines decide which sections
	// the artefact needs.
	pipelines := map[blueprint.Signal]pipeline{}
	for _, s := range blueprint.Signals {
		entries := bp.Lane(s)
		if len(entries) == 0 {
			continue
		}
		p, laneProblems := compileLane(in.Estate, bp, string(s), entries, ctx)
		problems = append(problems, laneProblems...)
		pipelines[s] = p
	}

	// The untrusted-Hop strip (REQ-034, ADR-0007): any untrusted arrival
	// makes the whole intake untrusted — one Tier renders one artefact for
	// all its collectors, so intake cannot split per Hop. The generated
	// processor runs first in every signal pipeline: nothing may observe the
	// platform namespace on inbound data before the strip.
	strip := tier.Untrusted() && len(pipelines) > 0
	if strip {
		for s, p := range pipelines {
			p.processors = append([]string{StripProcessorID}, p.processors...)
			pipelines[s] = p
		}
	}

	// service.extensions holds the collector-wide extensions in authored
	// order (ADR-0024 §2). Anything but an extension cannot live there.
	var serviceExtensions []string
	seenExt := map[string]bool{}
	for _, e := range bp.Extensions {
		c, ok := resolve(in.Estate, bp, e.Reference())
		if !ok {
			continue // already a mechanical refusal from resolveInstances
		}
		if c.Class != catalogue.Extension {
			problems = append(problems, fmt.Sprintf("%s: extensions block references %s, a %s — only extensions are collector-wide (ADR-0024 §2)", ctx, c.ID(), c.Class))
			continue
		}
		id := RenderedID(c)
		if !seenExt[id] {
			seenExt[id] = true
			serviceExtensions = append(serviceExtensions, id)
		}
	}

	if len(problems) > 0 {
		return nil, problems
	}

	root := mapping()
	root.HeadComment = fmt.Sprintf(
		"Generated by the telecraft renderer — humans never commit here (ADR-0027, ADR-0028).\nTier %s (%s), Blueprint %s, commit %s.",
		tier.ID(), tier.Environment, tier.Binding(), in.Commit)

	// Definition sections, one per class, ids sorted within each.
	sections := map[catalogue.Class]*yaml.Node{}
	for _, id := range sortedKeys(instances) {
		c := instances[id].comp
		section, ok := sections[c.Class]
		if !ok {
			section = mapping()
			sections[c.Class] = section
		}
		def, err := configNode(c.Config)
		if err != nil {
			return nil, []string{fmt.Sprintf("%s: Component %s: %v", ctx, c.ID(), err)}
		}
		appendPair(section, scalar(id), def)
	}
	if strip {
		section, ok := sections[catalogue.Processor]
		if !ok {
			section = mapping()
			sections[catalogue.Processor] = section
		}
		def, err := configNode(map[string]any{
			"actions": []any{map[string]any{"action": "delete", "pattern": `^telecraft\.`}},
		})
		if err != nil {
			return nil, []string{fmt.Sprintf("%s: %v", ctx, err)}
		}
		key := scalar(StripProcessorID)
		key.HeadComment = "Generated: data crossing an untrusted Hop sheds the platform's\nattribute namespace; identity is re-derived from this Tier's own\nstamps, never from inbound data (REQ-034, ADR-0007, ADR-0013)."
		// The strip runs first in every pipeline, so its definition leads
		// the section too, keeping the artefact legible top to bottom.
		prependPair(section, key, def)
	}
	for _, class := range []struct {
		class   catalogue.Class
		section string
	}{
		{catalogue.Receiver, "receivers"},
		{catalogue.Processor, "processors"},
		{catalogue.Exporter, "exporters"},
		{catalogue.Connector, "connectors"},
		{catalogue.Extension, "extensions"},
	} {
		if s, ok := sections[class.class]; ok {
			appendPair(root, scalar(class.section), s)
		}
	}

	// The service block: extensions, pipelines in the fixed signal order,
	// then telemetry with the identity stamps.
	service := mapping()
	if len(serviceExtensions) > 0 {
		appendPair(service, scalar("extensions"), sequence(serviceExtensions))
	}
	if len(pipelines) > 0 {
		pipelinesNode := mapping()
		for _, s := range blueprint.Signals {
			p, ok := pipelines[s]
			if !ok {
				continue
			}
			laneNode := mapping()
			appendPair(laneNode, scalar("receivers"), sequence(p.receivers))
			if len(p.processors) > 0 {
				appendPair(laneNode, scalar("processors"), sequence(p.processors))
			}
			appendPair(laneNode, scalar("exporters"), sequence(p.exporters))
			appendPair(pipelinesNode, scalar(string(s)), laneNode)
		}
		appendPair(service, scalar("pipelines"), pipelinesNode)
	}

	resource := mapping()
	nodeKey := scalar("k8s.node.name")
	nodeKey.HeadComment = fmt.Sprintf("Node-unique identity via the Downward API: install guidance feeds\n%s from spec.nodeName, so one DaemonSet manifest\nyields per-node identity (REQ-034, ADR-0010).", NodeEnvVar)
	appendPair(resource, nodeKey, scalar(fmt.Sprintf("${env:%s}", NodeEnvVar)))
	commitKey := scalar(CommitAttribute)
	commitKey.HeadComment = "The artefact carries its own identity (ADR-0013)."
	appendPair(resource, commitKey, scalar(in.Commit))
	telemetry := mapping()
	appendPair(telemetry, scalar("resource"), resource)
	appendPair(service, scalar("telemetry"), telemetry)

	appendPair(root, scalar("service"), service)

	return marshalDocument(root)
}

// emitSupervisor builds the Supervisor config served beside a Tier's
// collector artefact (REQ-032). The generated defaults are ADR-0010's
// install hard rules: remote config explicitly enabled, rollback on, state
// on a durable path.
func emitSupervisor(in Inputs, tier Tier) []byte {
	root := mapping()
	root.HeadComment = fmt.Sprintf(
		"Generated by the telecraft renderer — humans never commit here (ADR-0027, ADR-0028).\nSupervisor config for Tier %s, commit %s (ADR-0010).",
		tier.ID(), in.Commit)

	server := mapping()
	appendPair(server, scalar("endpoint"), scalar(tier.Serving.Endpoint))
	appendPair(root, scalar("server"), server)

	capabilities := mapping()
	acceptsKey := scalar("accepts_remote_config")
	acceptsKey.HeadComment = "Off upstream by default; serving is the point (ADR-0010)."
	appendPair(capabilities, acceptsKey, boolScalar(true))
	appendPair(capabilities, scalar("reports_effective_config"), boolScalar(true))
	appendPair(capabilities, scalar("reports_health"), boolScalar(true))
	appendPair(root, scalar("capabilities"), capabilities)

	agent := mapping()
	rollbackKey := scalar("automatic_config_rollback")
	rollbackKey.HeadComment = "Revert-on-failure is off by default upstream (ADR-0010)."
	appendPair(agent, rollbackKey, boolScalar(true))
	appendPair(root, scalar("agent"), agent)

	storage := mapping()
	dirKey := scalar("directory")
	dirKey.HeadComment = "A durable volume — an ephemeral directory mints a new identity\nper pod replacement (ADR-0010)."
	appendPair(storage, dirKey, scalar(SupervisorStorageDir))
	appendPair(root, scalar("storage"), storage)

	out, _ := marshalDocument(root)
	return out
}

// mapping returns an empty block-style mapping node.
func mapping() *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
}

// scalar returns a plain scalar node for a string value.
func scalar(s string) *yaml.Node {
	n := &yaml.Node{}
	n.SetString(s)
	return n
}

func boolScalar(b bool) *yaml.Node {
	n := &yaml.Node{}
	if err := n.Encode(b); err != nil {
		panic(err) // encoding a bool cannot fail
	}
	return n
}

// sequence returns a block sequence of plain scalars.
func sequence(values []string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, v := range values {
		n.Content = append(n.Content, scalar(v))
	}
	return n
}

func appendPair(m, key, value *yaml.Node) {
	m.Content = append(m.Content, key, value)
}

func prependPair(m, key, value *yaml.Node) {
	m.Content = append([]*yaml.Node{key, value}, m.Content...)
}

// configNode encodes a Component's opaque config body with every mapping
// recursively sorted by key. The body is authored YAML and its in-memory
// form is a Go map, so nothing about it has an order of its own — sorting
// is what makes the emission a pure function of content (ADR-0028 §2).
func configNode(v any) (*yaml.Node, error) {
	if v == nil {
		return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Style: yaml.FlowStyle}, nil
	}
	n := &yaml.Node{}
	if err := n.Encode(v); err != nil {
		return nil, fmt.Errorf("config does not encode to YAML: %w", err)
	}
	sortMappings(n)
	return n, nil
}

// sortMappings sorts every mapping in the node tree by key, in place.
func sortMappings(n *yaml.Node) {
	for _, c := range n.Content {
		sortMappings(c)
	}
	if n.Kind != yaml.MappingNode {
		return
	}
	pairs := make([][2]*yaml.Node, 0, len(n.Content)/2)
	for i := 0; i+1 < len(n.Content); i += 2 {
		pairs = append(pairs, [2]*yaml.Node{n.Content[i], n.Content[i+1]})
	}
	sort.SliceStable(pairs, func(i, j int) bool { return pairs[i][0].Value < pairs[j][0].Value })
	n.Content = n.Content[:0]
	for _, p := range pairs {
		n.Content = append(n.Content, p[0], p[1])
	}
}

// marshalDocument renders a root node with the repo's two-space indent.
func marshalDocument(root *yaml.Node) ([]byte, []string) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, []string{fmt.Sprintf("artefact does not encode to YAML: %v", err)}
	}
	if err := enc.Close(); err != nil {
		return nil, []string{fmt.Sprintf("artefact does not encode to YAML: %v", err)}
	}
	return buf.Bytes(), nil
}
